export const SEARCH_BLOCKS = 'SEARCH_BLOCKS';
export const SEARCH_BLOCKS_PENDING = 'SEARCH_BLOCKS_PENDING';
export const SEARCH_BLOCKS_SUCCESS = 'SEARCH_BLOCKS_SUCCESS';
export const SEARCH_BLOCKS_FAIL = 'SEARCH_BLOCKS_FAIL';
